# Generated by Django 6.0.6 on 2026-07-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='queixa',
            field=models.CharField(choices=[('D', 'Depressão'), ('A', 'Ansiedade')], max_length=1),
        ),
    ]
